version: '3.2'
services:
  kanastra_application:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kanastra_application
    volumes:
      - ./:/app
    ports:
      - "8091:8000"
    depends_on:
      - kanastra_db
      - kanastra_redis
    networks:
      - kanastra

  kanastra_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: kanastra_db
    restart: always
    ports:
      - "3391:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanastra
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - kanastra

  kanastra_redis:
    image: redis:7.0.2
    container_name: kanastra_redis
    restart: always
    ports:
      - "6391:6379"
    volumes:
      - ./docker/redis:/data
    networks:
      - kanastra

networks:
  kanastra:
    driver: bridge